#!/bin/bash
echo "=== Checking Watch App Files ==="
echo ""
echo "Files that should be in Watch App target:"
echo ""
echo "1. WatchApp.swift:"
ls -1 "Do/Do Watch App/WatchApp.swift" 2>/dev/null && echo "   ✓ Found" || echo "   ✗ Missing"
echo ""
echo "2. WatchConnectivityManager.swift:"
ls -1 "Do/Do Watch App/Services/WatchConnectivityManager.swift" 2>/dev/null && echo "   ✓ Found" || echo "   ✗ Missing"
echo ""
echo "3. WatchWorkoutCoordinator.swift:"
ls -1 "Do/Do Watch App/Services/WatchWorkoutCoordinator.swift" 2>/dev/null && echo "   ✓ Found" || echo "   ✗ Missing"
echo ""
echo "4. WatchAuthService.swift:"
ls -1 "Do/Do Watch App/Services/WatchAuthService.swift" 2>/dev/null && echo "   ✓ Found" || echo "   ✗ Missing"
echo ""
echo "All files exist. If you're getting 'Cannot find in scope' errors,"
echo "the files may not be added to the Watch App target in Xcode."
echo ""
echo "To fix in Xcode:"
echo "1. Select each file in the Project Navigator"
echo "2. Open File Inspector (right panel)"
echo "3. Under 'Target Membership', ensure 'Do Watch App' is checked"
